# PURL configuration for http://purl.obolibrary.org/obo/chebi

idspace: CHEBI
base_url: /obo/chebi

products:
- chebi.owl: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl
- chebi.obo: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.obo
- chebi.owl.gz: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl.gz
- chebi.obo.gz: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.obo.gz

term_browser: custom

entries:
- exact: /tracker
  replacement: https://github.com/ebi-chebi/ChEBI/issues

- exact: /browse
  replacement: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A24431

- exact: /internal/chebi-disjoints.owl
  replacement: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi-disjoints.owl

- exact: /internal/chebi-in-bfo.owl
  replacement: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi-in-bfo.owl

- exact: /internal/chebi.owl
  replacement: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl
 
- exact: /obophenotype/chebi_slim.owl
  replacement: https://raw.githubusercontent.com/obophenotype/chebi_obo_slim/master/chebi_slim.owl

- exact: /obophenotype/chebi_slim.obo
  replacement: https://raw.githubusercontent.com/obophenotype/chebi_obo_slim/master/chebi_slim.obo

- prefix: /obophenotype/releases/
  replacement: https://raw.githubusercontent.com/obophenotype/chebi_obo_slim/v
  tests:
    - from: /obophenotype/releases/2022-09-03/chebi_slim.obo
      to: https://raw.githubusercontent.com/obophenotype/chebi_obo_slim/v2022-09-03/chebi_slim.obo

- prefix: /about/
  replacement: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=
  tests:
  - from: /about/CHEBI_15377
    to: http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI_15377

- regex: ^/obo/chebi/(\d+)/(.+)$
  replacement: http://ftp.ebi.ac.uk/pub/databases/chebi/archive/rel$1/ontology/$2
  tests:
  - from: /186/chebi.owl
    to: http://ftp.ebi.ac.uk/pub/databases/chebi/archive/rel186/ontology/chebi.owl

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/
